# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    Sylius\ShopApiPlugin\Handler\Cart\ChooseShippingMethodCustomHandler:
        class: App\Handler\Cart\ChooseShippingMethodCustomHandler
        decorates: sylius.shop_api_plugin.handler.choose_shipping_method_handler
        tags:
            -
                name: messenger.message_handler
#                bus: sylius_default.bus
                # only needed if can't be guessed by type-hint
                handles: App\Handler\Cart\ChooseShippingMethodCustom
#        arguments: [ '@app.factory.product.inner' ]
    #    sylius.shop_api_plugin.handler.choose_shipping_method_handler:
#        class: '@App\Handler\Cart\ChooseShippingMethodCustomHandler'
#        arguments: ['@sylius.shop_api_plugin.handler.choose_shipping_method_handler']


#    App\Handler\Cart\ChooseShippingMethodCustomHandler:
#        arguments:
##            - '@sylius.repository.order'
##            - '@sylius.repository.shipping_method'
##            - '@sylius.shipping_method_eligibility_checker'
#            - '@sm.factory'
#        # or configure with options
#        tags:
#            -
#                name: messenger.message_handler
##                bus: sylius_default.bus
#                # only needed if can't be guessed by type-hint
#                handles: App\Handler\Cart\ChooseShippingMethodCustom
#
#    app.factory.product:
#        class: App\Factory\ProductFactory
#        decorates: sylius.factory.product
#        arguments: ['@app.factory.product.inner']
#        public: false
